language: node_js
node_js:
  - "10.15.3"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
  - npm install -g codecov
script:
  - npm install
  - npm run build
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
