language: node_js
node_js:
  - "10.15.3"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
  - npm install -g codecov
  - npm install -g istanbul
script:
  - npm install
  - npm run build
  - npm run test --code-coverage --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - codecov
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
